### PR TITLE
Fixed memory leaks in window.SetTimeout and window.SetInterval

### PR DESCRIPTION
**Pull request by TheQwertiest**
Sorry for the formatting.

### CODE REVIEW

**Comment by marc2k3** [comment]
Can't say I'd noticed any problems before - memory usage has always remained stable for me without increasing over time. Still I appreciate the fix. I'll try and hammer it over the next few hours before merging!!

**Comment by kbuffington** [comment]
I hadn't noticed any memory leaks either, but my themes have stopped making as much use of Timeouts/Intervals. Can you point out in the commit where the leak was actually happening?

**Comment by TheQwertiest** [comment]
The leak is not that big - maybe 40 bytes per `SetInterval`/`SetTimeout`, but it's still a leak :D

@kbuffington : well, as embarrassing as it is, it is actually my re-implementation that introduced the leak (https://github.com/marc2k3/foo_jscript_panel/commit/f9f07318e894357a0b1a7cd1bb21052a151154d2#diff-80df433453cb3352fdb3ab66aab072a5). And I don't like leaving mistakes in my wake =)

**Comment by marc2k3** [comment]
Thanks!

**Pull request merged**
